---
vhosts:
  - name: www.briefcasetype.com
    aliases:
      - www.briefcasetype.com
      - briefcasetype.com
    repo: git@github.com:LastStar/bbct
    environment: production
  - name: beta.briefcasetype.com
    aliases:
      - beta.briefcasetype.com
    repo: git@github.com:LastStar/bbct
    environment: staging
  - name: www.suitcasetype.com
    aliases:
      - www.suitcasetype.com
      - suitcasetype.com
    repo: git@github.com:LastStar/sct
    environment: production
  - name: beta.suitcasetype.com
    aliases:
      - beta.suitcasetype.com
    repo: git@github.com:LastStar/sct
    environment: staging
