---
- name: Upgrade apt packages
  apt: upgrade=yes
       update_cache=yes

- name: Install GIT
  apt: name=git
       state=latest

- name: Install NTP
  apt: pkg=ntp
       state=latest

- name: Install Vim
  apt: pkg=vim
       state=latest

- name: Install prerequisite packages that are necessary to compile applications and gems with native extensions
  apt: pkg={{ item }}
  with_items:
    - autoconf
    - build-essential

- name: Install python-software-properties so the apt_repository module will work properly
  apt: pkg=python-software-properties

- name: Create src directory
  file: path=/usr/src owner=deploy group=deploy state=directory

- name: Create www directory
  file: path=/usr/www owner=deploy group=deploy state=directory


